// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Whatever.Data;

namespace Whatever.Migrations
{
    [DbContext(typeof(WhateverDbContext))]
    partial class WhateverDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Whatever.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstPlayerClass")
                        .IsRequired();

                    b.Property<string>("FirstPlayerEmail")
                        .IsRequired();

                    b.Property<string>("FirstPlayerName")
                        .IsRequired();

                    b.Property<string>("FirstPlayerPhoneNumber");

                    b.Property<string>("FirstPlayerSchool")
                        .IsRequired();

                    b.Property<string>("SecondPlayerClass")
                        .IsRequired();

                    b.Property<string>("SecondPlayerEmail")
                        .IsRequired();

                    b.Property<string>("SecondPlayerName")
                        .IsRequired();

                    b.Property<string>("SecondPlayerPhoneNumber");

                    b.Property<string>("SecondPlayerSchool")
                        .IsRequired();

                    b.Property<string>("TeamName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
